# Generated by Django 5.1.6 on 2025-02-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fromconsignor_toconsignor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankerno', models.CharField(max_length=100)),
                ('tripdate', models.DateField(null=True)),
                ('tdate', models.DateField(null=True)),
                ('drivername', models.CharField(max_length=100)),
                ('fromconsignor', models.CharField(max_length=200)),
                ('toconsignee', models.CharField(max_length=200)),
                ('trip_general_expenses', models.IntegerField()),
                ('food_allowance', models.IntegerField()),
                ('bhatta', models.IntegerField()),
                ('washing_charges_tank', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
