# Generated by Django 5.2.1 on 2025-05-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vc_invoice_vc_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_item',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tb_item',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tb_item',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tb_item',
            name='lr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tb_item',
            name='tanker_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tb_item',
            name='to_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
