# Generated by Django 5.2.1 on 2025-05-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tb_item_dispatch_date_tb_item_from_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_item',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='tb_item',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='tb_item',
            name='hsn_sac',
        ),
        migrations.RemoveField(
            model_name='tb_item',
            name='lr_no',
        ),
        migrations.RemoveField(
            model_name='tb_item',
            name='tanker_no',
        ),
        migrations.RemoveField(
            model_name='tb_item',
            name='to_address',
        ),
        migrations.AddField(
            model_name='vc_item',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vc_item',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vc_item',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vc_item',
            name='lr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vc_item',
            name='tanker_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vc_item',
            name='to_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
