# Generated by Django 5.1.6 on 2025-02-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_truckno_ownername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driverdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(max_length=200)),
                ('adharno', models.IntegerField()),
                ('licenceno', models.CharField(max_length=20)),
                ('issuedate', models.DateField()),
                ('trdate', models.DateField()),
                ('imgupload', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
