# Generated by Django 5.2.1 on 2025-05-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tb_item_dispatch_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vc_item',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='vc_item',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='vc_item',
            name='hsn_sac',
        ),
        migrations.RemoveField(
            model_name='vc_item',
            name='lr_no',
        ),
        migrations.RemoveField(
            model_name='vc_item',
            name='tanker_no',
        ),
        migrations.RemoveField(
            model_name='vc_item',
            name='to_address',
        ),
    ]
