# Generated by Django 5.1.6 on 2025-02-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pdfupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetails',
            name='imgupload',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
