# Generated by Django 5.1.6 on 2025-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_driverdetails_imgupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDriverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adharnumber', models.IntegerField()),
                ('licencenumber', models.CharField(max_length=20)),
                ('issuedates', models.DateField()),
                ('trdates', models.DateField()),
                ('imguploads', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='PDFUpload',
        ),
    ]
