# Generated by Django 5.1.6 on 2025-02-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_driverdetails_imgupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdriverdetails',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
