# Generated by Django 5.2.1 on 2025-05-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_ashland_delete_harkaran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ashland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('gst', models.CharField(blank=True, max_length=300, null=True)),
                ('pan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanker', models.CharField(blank=True, max_length=200, null=True)),
                ('tanker_cap', models.CharField(blank=True, max_length=200, null=True)),
                ('From_add', models.CharField(blank=True, max_length=200, null=True)),
                ('To_add', models.CharField(blank=True, max_length=200, null=True)),
                ('date_dis', models.DateField(blank=True, null=True)),
                ('kg', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('total_kg', models.IntegerField(blank=True, null=True)),
                ('lr_no', models.IntegerField(blank=True, null=True)),
                ('Fo_date', models.DateField(blank=True, null=True)),
                ('To_date', models.DateField(blank=True, null=True)),
                ('d_rate', models.IntegerField(blank=True, null=True)),
                ('par_day', models.IntegerField(blank=True, null=True)),
                ('total_d', models.IntegerField(blank=True, null=True)),
                ('tank_c', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='harkaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('gst', models.CharField(blank=True, max_length=300, null=True)),
                ('pan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanker', models.CharField(max_length=200, null=True)),
                ('From_add', models.CharField(max_length=200, null=True)),
                ('To_add', models.CharField(max_length=200, null=True)),
                ('date_dis', models.DateField(blank=True, null=True)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lr_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='Fo_date',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='From_add',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='To_add',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='To_date',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='c_gst',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='d_rate',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='date_dis',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='fright_total',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='g_total',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='hsac',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='i_gst',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='lr_no',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='par_day',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='s_gst',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='sac',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='t_rate',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='tanker',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='tcharges',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='thsac',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='total_d',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='total_t',
        ),
        migrations.RemoveField(
            model_name='aitem',
            name='tpar_day',
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='Fo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='From_add',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='To_add',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='To_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='c_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='charges',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='d_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='date_dis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='fright_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='g_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='hsac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='i_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='lr_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='par_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='s_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='sac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='t_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='tanker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='tcharges',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='thsac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='total_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='total_t',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='tpar_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
