# Generated by Django 5.1.6 on 2025-02-25 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_newdriverdetails_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diesle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paidby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('paidby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.diesle')),
            ],
        ),
    ]
