# Generated by Django 5.1.6 on 2025-02-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_diesle_paidby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidby',
            old_name='paidby',
            new_name='diesle',
        ),
    ]
