# Generated by Django 5.2.1 on 2025-05-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ashland_harkaran_remove_aitem_fo_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ashland',
        ),
        migrations.DeleteModel(
            name='harkaran',
        ),
        migrations.AlterField(
            model_name='ainvoice',
            name='g_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
