# Generated by Django 5.1.6 on 2025-02-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanker_no', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('bill_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('trip_general_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_allowances', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bhatta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('washing_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tank')),
            ],
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diesel_name', models.CharField(max_length=100)),
                ('liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_by', models.CharField(max_length=100)),
                ('amount_given', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.trip')),
            ],
        ),
    ]
