# Generated by Django 5.2.1 on 2025-05-31 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_veinvoice_remove_ainvoice_c_gst_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VEInvoice',
            new_name='SAInvoice',
        ),
        migrations.RenameModel(
            old_name='VEItem',
            new_name='SAItem',
        ),
    ]
