# Generated by Django 5.1.6 on 2025-02-25 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_tank_trip_tripdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_address', models.CharField(max_length=200)),
                ('To_address', models.CharField(max_length=200)),
                ('tanker_capacity', models.CharField(max_length=200)),
                ('tankerno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tankerno')),
            ],
        ),
    ]
