# Generated by Django 5.2.1 on 2025-05-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_veinvoice_sainvoice_rename_veitem_saitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ainvoice',
            name='t_rate',
        ),
        migrations.RemoveField(
            model_name='ainvoice',
            name='total_t',
        ),
        migrations.RemoveField(
            model_name='ainvoice',
            name='tpar_day',
        ),
    ]
