# Generated by Django 5.2.1 on 2025-05-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_ainvoice_t_rate_remove_ainvoice_total_t_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ainvoice',
            old_name='charges',
            new_name='tcharges',
        ),
    ]
