# Generated by Django 5.1.6 on 2025-02-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_companydetails_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='dispatch_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
