# Generated by Django 5.1.6 on 2025-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_plans_dispatch_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='plandetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankerno', models.CharField(max_length=200)),
                ('tanks', models.CharField(max_length=200)),
                ('From_address', models.CharField(max_length=200)),
                ('To_address', models.CharField(max_length=200)),
                ('tanker_capacity', models.CharField(max_length=200)),
                ('dispatch_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
