# Generated by Django 5.2.1 on 2025-05-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_charges_ainvoice_tcharges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ainvoice',
            old_name='tcharges',
            new_name='charges',
        ),
    ]
