# Generated by Django 5.2.1 on 2025-05-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_tcharges_ainvoice_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ainvoice',
            old_name='charges',
            new_name='charges_tank',
        ),
    ]
