# Generated by Django 5.2.1 on 2025-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_charges_ainvoice_charges_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainvoice',
            name='c_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='g_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='i_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='s_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
