# Generated by Django 5.1.6 on 2025-02-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_companydetails_area_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='gst_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='pan_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
