# Generated by Django 5.2.1 on 2025-06-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_ainvoice_c_gst_ainvoice_g_total_ainvoice_i_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='toll_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
