# Generated by Django 5.1.6 on 2025-02-25 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_companydetails_contact_no_companydetails_gst_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='gst_no',
        ),
        migrations.RemoveField(
            model_name='companydetails',
            name='pan_no',
        ),
        migrations.CreateModel(
            name='TankerCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tankerno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tankerno')),
            ],
        ),
    ]
