# Generated by Django 5.1.6 on 2025-02-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_companydetails_gst_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='plandetails',
            name='status',
            field=models.CharField(choices=[('DISPATCH', 'dispatch'), ('ARRIVAL', 'arrival'), ('DEPARTURE', 'departure')], default='dispatch', max_length=100),
        ),
        migrations.CreateModel(
            name='SubCategory2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category2')),
            ],
        ),
    ]
