# Generated by Django 5.2.1 on 2025-06-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_expense_toll_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_qty', models.IntegerField()),
                ('item_date', models.DateField()),
                ('vendor_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='toll_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanker', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('person_name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
        ),
    ]
