# Generated by Django 5.1.6 on 2025-02-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_category2_plandetails_status_subcategory2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driverdetails',
        ),
        migrations.AlterField(
            model_name='newdriverdetails',
            name='img',
            field=models.FileField(null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='plandetails',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
