# Generated by Django 5.1.6 on 2025-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_delete_driverdetails_alter_newdriverdetails_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdriverdetails',
            name='imguploads',
            field=models.FileField(upload_to='img/'),
        ),
    ]
