# Generated by Django 5.2.1 on 2025-06-04 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_transaction_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UsedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanker', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('person_name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('used_on', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.items')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
