# Generated by Django 5.1.6 on 2025-02-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_newdriverdetails_imguploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='TollDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankerno', models.CharField(max_length=200)),
                ('driver_name', models.CharField(max_length=200)),
                ('trip_date', models.DateField()),
                ('date', models.DateField()),
                ('toll_name', models.CharField(max_length=200)),
                ('From_address', models.CharField(max_length=200)),
                ('To_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plandetails',
            name='tanker_capacity',
            field=models.CharField(max_length=2),
        ),
    ]
