# Generated by Django 5.2.1 on 2025-06-04 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_items_item_qty_useditem_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.items'),
        ),
    ]
