# Generated by Django 5.1.6 on 2025-02-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_tolldetails_trip_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tolldetails',
            old_name='driver_name',
            new_name='driver_names',
        ),
    ]
