# Generated by Django 5.2.1 on 2025-06-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_useditem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='useditem',
            name='item_use',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
