# Generated by Django 5.1.6 on 2025-02-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_driver_name_tolldetails_driver_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toll_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankerno', models.CharField(max_length=200)),
                ('driver_names', models.CharField(max_length=200)),
                ('trip_date', models.DateField()),
                ('date', models.DateField()),
                ('amount', models.DateField()),
                ('toll_name', models.CharField(max_length=200)),
                ('From_address', models.CharField(max_length=200)),
                ('To_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TollDetails',
        ),
    ]
