# Generated by Django 5.1.6 on 2025-02-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_toll_details_delete_tolldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toll_details',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
