# Generated by Django 5.2.1 on 2025-06-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_useditem_item_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useditem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='useditem',
            name='item_use',
        ),
    ]
