# Generated by Django 5.2.1 on 2025-06-04 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_useditem_date_remove_useditem_item_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useditem',
            name='used_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
