# Generated by Django 5.1.6 on 2025-02-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_toll_details_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toll_details',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='toll_details',
            name='trip_date',
            field=models.DateField(null=True),
        ),
    ]
