# Generated by Django 5.2.1 on 2025-06-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_useditem_used_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useditem',
            name='used_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
