# Generated by Django 5.1.6 on 2025-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_toll_details_date_alter_toll_details_trip_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankerno_diesel', models.CharField(max_length=200)),
                ('tripdate_diesel', models.DateField(null=True)),
                ('date_diesel', models.DateField(null=True)),
                ('category', models.CharField(max_length=200)),
                ('subCategory', models.IntegerField()),
                ('paid_by', models.IntegerField()),
                ('liters', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_diesel_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='subcategory2',
            name='category',
        ),
        migrations.RemoveField(
            model_name='paidby',
            name='diesle',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
        migrations.DeleteModel(
            name='SubCategory2',
        ),
        migrations.DeleteModel(
            name='Diesle',
        ),
        migrations.DeleteModel(
            name='Paidby',
        ),
    ]
