# Generated by Django 5.2.1 on 2025-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_useditem_used_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=200)),
                ('tool_qty', models.PositiveIntegerField(default=0)),
                ('tool_date', models.DateField()),
                ('vendor_name', models.CharField(max_length=200)),
            ],
        ),
    ]
