# Generated by Django 5.1.6 on 2025-02-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_dieseldetails_remove_subcategory2_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieseldetails',
            name='subCategory',
            field=models.CharField(max_length=200),
        ),
    ]
