# Generated by Django 5.1.6 on 2025-03-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_dieseldetails_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieseldetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankerno_diesel', models.CharField(max_length=200)),
                ('tripdate_diesel', models.DateField(null=True)),
                ('date_diesel', models.DateField(null=True)),
                ('category', models.CharField(max_length=200)),
                ('subCategory', models.CharField(max_length=200)),
                ('paid_by', models.CharField(max_length=200)),
                ('paid_to', models.CharField(max_length=200)),
                ('liters', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_diesel', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='DieselDetails',
        ),
    ]
