# Generated by Django 5.2.1 on 2025-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_inout'),
    ]

    operations = [
        migrations.AddField(
            model_name='inout',
            name='entry',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inout',
            name='fire',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inout',
            name='kit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inout',
            name='tankercapacity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inout',
            name='tankercondition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inout',
            name='tankertype',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
