# Generated by Django 5.2.1 on 2025-06-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_inout_entry_inout_fire_inout_kit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inout',
            name='intitme',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='inout',
            name='outtitme',
            field=models.DateTimeField(null=True),
        ),
    ]
