# Generated by Django 5.1.6 on 2025-03-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_add_vehicle_remove_newdriverdetails_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_vehicle',
            name='From_address',
        ),
        migrations.RemoveField(
            model_name='add_vehicle',
            name='To_address',
        ),
        migrations.RemoveField(
            model_name='add_vehicle',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='add_vehicle',
            name='toll_name',
        ),
    ]
