# Generated by Django 5.2.1 on 2025-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_inout_intitme_alter_inout_outtitme'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='pending_trip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
