# Generated by Django 5.1.6 on 2025-03-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_add_vehicle_from_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPetrolPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DriverName',
        ),
        migrations.DeleteModel(
            name='FromConsignor',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='tank',
        ),
        migrations.RemoveField(
            model_name='tankercapacity',
            name='tankerno',
        ),
        migrations.DeleteModel(
            name='ToConsignor',
        ),
        migrations.RemoveField(
            model_name='tripdetails',
            name='trip',
        ),
        migrations.DeleteModel(
            name='Tank',
        ),
        migrations.DeleteModel(
            name='TankerNo',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripDetails',
        ),
    ]
