# Generated by Django 5.2.1 on 2025-06-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_trip_pending_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usetool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=200)),
                ('person_name', models.CharField(max_length=200)),
                ('tool_category', models.CharField(max_length=200)),
                ('tool_condition', models.CharField(max_length=200)),
                ('tool_take', models.DateTimeField(null=True)),
                ('tool_return', models.DateTimeField(null=True)),
                ('issue', models.CharField(max_length=200, null=True)),
                ('use_of', models.TextField()),
            ],
        ),
    ]
