# Generated by Django 5.2.1 on 2025-06-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_usetool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usetool',
            name='tool_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usetool',
            name='tool_condition',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
