# Generated by Django 5.1.6 on 2025-03-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_addpetrolpump_delete_drivername_delete_fromconsignor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDriver_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adharnumber', models.IntegerField()),
                ('licencenumber', models.CharField(max_length=20)),
                ('issuedates', models.DateField()),
                ('trdates', models.DateField()),
                ('img', models.FileField(null=True, upload_to='img')),
            ],
        ),
        migrations.DeleteModel(
            name='NewDriverDetails',
        ),
    ]
