# Generated by Django 5.2.1 on 2025-06-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_usetool_tool_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanke', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('date', models.DateTimeField(null=True)),
                ('remark', models.TextField()),
            ],
        ),
    ]
