# Generated by Django 5.1.6 on 2025-03-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_newdriver_details_delete_newdriverdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Urea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urea_tanker_no', models.CharField(max_length=200)),
                ('From_address', models.CharField(max_length=200)),
                ('To_address', models.CharField(max_length=200)),
                ('paid_date', models.DateField(null=True)),
                ('bill_date', models.DateField(null=True)),
                ('trip_urea_date', models.DateField(null=True)),
                ('urea_liter', models.IntegerField()),
                ('urea_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('urea_total', models.DecimalField(decimal_places=4, max_digits=10)),
                ('chassise_no', models.CharField(max_length=200)),
                ('engine_no', models.CharField(max_length=200)),
                ('insurance_date', models.DateField(null=True)),
                ('state_permit', models.DateField(null=True)),
                ('national_permit', models.DateField(null=True)),
                ('fitness_date', models.DateField(null=True)),
                ('tax_date', models.DateField(null=True)),
                ('puc_date', models.DateField(null=True)),
            ],
        ),
    ]
