# Generated by Django 5.1.6 on 2025-03-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_add_urea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_urea',
            name='chassise_no',
        ),
        migrations.RemoveField(
            model_name='add_urea',
            name='engine_no',
        ),
        migrations.RemoveField(
            model_name='add_urea',
            name='fitness_date',
        ),
        migrations.RemoveField(
            model_name='add_urea',
            name='insurance_date',
        ),
        migrations.RemoveField(
            model_name='add_urea',
            name='national_permit',
        ),
        migrations.RemoveField(
            model_name='add_urea',
            name='puc_date',
        ),
        migrations.RemoveField(
            model_name='add_urea',
            name='state_permit',
        ),
        migrations.RemoveField(
            model_name='add_urea',
            name='tax_date',
        ),
    ]
