# Generated by Django 5.2.1 on 2025-06-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='driverloan',
            name='trip_date',
            field=models.DateField(null=True),
        ),
    ]
