# Generated by Django 5.1.6 on 2025-03-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_all_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_trip',
            name='trip_urea_date',
        ),
    ]
