# Generated by Django 5.1.6 on 2025-03-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_all_trip_trip_urea_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_trip',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='given_amounts_diesel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='no_piece',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='r_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='r_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='spare_part',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='total_diesel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='tripdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='urea_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='urea_total',
            field=models.IntegerField(null=True),
        ),
    ]
