# Generated by Django 5.2.1 on 2025-06-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_plandetails_used_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='used_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
