# Generated by Django 5.2.1 on 2025-06-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_trip_used_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='tool_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
