# Generated by Django 5.1.6 on 2025-03-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_all_trip_amount_alter_all_trip_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_trip',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='bhatta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='food_allowance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='given_amounts_diesel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='liters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='no_piece',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='paid_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='part_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='r_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='spare_part',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='subCategory',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='tdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='toll_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='total_diesel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='trip_general_expenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='tripdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='urea_liter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='urea_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='urea_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='washing_charges_tank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
