# Generated by Django 5.1.6 on 2025-03-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_all_trip_amount_alter_all_trip_bhatta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_trip',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip',
            name='tripdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
