# Generated by Django 5.2.1 on 2025-06-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_usetool_tool_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usetool',
            old_name='tool_name',
            new_name='tool',
        ),
    ]
