# Generated by Django 5.1.6 on 2025-03-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_trip_end_remove_all_trip_expense_trip_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_Date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='date',
        ),
        migrations.RemoveField(
            model_name='trip_end',
            name='trip_end',
        ),
    ]
