# Generated by Django 5.2.1 on 2025-06-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_crinvoice_date_dis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crinvoice',
            name='Fo_date',
        ),
        migrations.RemoveField(
            model_name='crinvoice',
            name='To_date',
        ),
    ]
