# Generated by Django 5.1.6 on 2025-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_endtrip_delete_date_remove_trip_end_trip_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_end',
            name='End_Date',
            field=models.DateField(null=True),
        ),
    ]
