# Generated by Django 5.1.6 on 2025-03-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_trip_end_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip_end',
            old_name='End_Date',
            new_name='end_date',
        ),
    ]
