# Generated by Django 5.2.1 on 2025-06-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_ve_invoice_ve_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='ve_invoice',
            name='fassi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ve_invoice',
            name='tan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
