# Generated by Django 5.1.6 on 2025-03-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_rename_end_date_trip_end_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_trip_expense',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
