# Generated by Django 5.2.1 on 2025-06-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_ve_invoice_fassi_ve_invoice_tan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanker', models.CharField(max_length=200)),
                ('from_add', models.CharField(max_length=200)),
                ('to_add', models.CharField(max_length=200)),
                ('trip', models.DateField()),
                ('bill', models.DateField()),
                ('company', models.CharField(max_length=200)),
                ('expese', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
