# Generated by Django 5.1.6 on 2025-03-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_tanker_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='tanker',
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='bhatta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='food_allowance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='given_amounts_diesel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='liters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='r_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='total_diesel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='trip_general_expenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_end',
            name='washing_charges_tank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Tanker',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
