# Generated by Django 5.2.1 on 2025-06-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_rrinvoice_rritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='driverloan',
            name='previous_loan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
