# Generated by Django 5.1.6 on 2025-03-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_delete_trip_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_trip_expense',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip_expense',
            name='bhatta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip_expense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip_expense',
            name='food_allowance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip_expense',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip_expense',
            name='trip_general_expenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_trip_expense',
            name='washing_charges_tank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
