# Generated by Django 5.2.1 on 2025-06-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_nhtinvoice_nhtitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
