# Generated by Django 5.2.1 on 2025-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_driverloan_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverloan',
            name='trip_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
