# Generated by Django 5.1.6 on 2025-03-06 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_trip_expense_delete_all_trip_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_expense',
            name='trip_tanker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_vehicle'),
        ),
    ]
