# Generated by Django 5.2.1 on 2025-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_driverloan_date_alter_driverloan_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='previous_loan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
