# Generated by Django 5.2.1 on 2025-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_driverloan_previous_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='previous_loan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
