# Generated by Django 5.1.6 on 2025-03-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_trip_expense_trip_tanker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_expense',
            name='trip_tanker',
            field=models.CharField(max_length=200),
        ),
    ]
