# Generated by Django 5.1.6 on 2025-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_trip_expense_trip_tanker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_expense',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_expense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_expense',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_expense',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_expense',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_expense',
            name='tripdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
