# Generated by Django 5.1.6 on 2025-03-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_trip_expense_bill_date_alter_trip_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_expense',
            name='r_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip_expense',
            name='r_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
