# Generated by Django 5.2.1 on 2025-07-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_mainvoice_maitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='short_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
