# Generated by Django 5.1.6 on 2025-03-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_trip_expense_r_bill_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_expense',
            name='end_date',
        ),
    ]
