# Generated by Django 5.1.6 on 2025-03-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_trip_expense_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_expense',
            name='trip_tanker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
