# Generated by Django 5.1.6 on 2025-03-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_trip_expense_trip_tanker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_tanker', models.CharField(blank=True, max_length=100, null=True)),
                ('tripdate', models.DateField(blank=True, null=True)),
                ('tdate', models.DateField(blank=True, null=True)),
                ('drivername', models.CharField(max_length=100)),
                ('From_address', models.CharField(max_length=200)),
                ('To_address', models.CharField(max_length=200)),
                ('trip_general_expenses', models.IntegerField()),
                ('food_allowance', models.IntegerField()),
                ('bhatta', models.IntegerField()),
                ('washing_charges_tank', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('toll_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('subCategory', models.CharField(blank=True, max_length=200)),
                ('paid_to', models.CharField(blank=True, max_length=200, null=True)),
                ('given_amounts_diesel', models.IntegerField()),
                ('liters', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('total_diesel', models.IntegerField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('urea_liter', models.IntegerField()),
                ('urea_rate', models.IntegerField()),
                ('urea_total', models.IntegerField()),
                ('r_paid_date', models.DateField(blank=True, null=True)),
                ('r_bill_date', models.DateField(blank=True, null=True)),
                ('spare_part', models.IntegerField()),
                ('r_amount', models.IntegerField()),
                ('part_name', models.CharField(max_length=200)),
                ('no_piece', models.IntegerField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
