# Generated by Django 5.2.1 on 2025-07-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_hwinvoice_hwitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hwitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='HWInvoice',
        ),
        migrations.DeleteModel(
            name='HWItem',
        ),
    ]
