# Generated by Django 5.1.6 on 2025-03-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_report_all'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report_all',
        ),
        migrations.RenameField(
            model_name='plandetails',
            old_name='tanks',
            new_name='drivername',
        ),
    ]
