# Generated by Django 5.2.1 on 2025-07-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_hwinvoice_hwitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
