# Generated by Django 5.1.6 on 2025-03-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_addtrips_alter_newdriver_details_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrips',
            name='trip_general_expenses',
            field=models.IntegerField(null=True),
        ),
    ]
