# Generated by Django 5.1.6 on 2025-03-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_addtrips_trip_general_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtrips',
            name='bhatta',
        ),
        migrations.RemoveField(
            model_name='addtrips',
            name='food_allowance',
        ),
        migrations.RemoveField(
            model_name='addtrips',
            name='fromconsignor',
        ),
        migrations.RemoveField(
            model_name='addtrips',
            name='tdate',
        ),
        migrations.RemoveField(
            model_name='addtrips',
            name='toconsignee',
        ),
        migrations.RemoveField(
            model_name='addtrips',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='addtrips',
            name='trip_general_expenses',
        ),
        migrations.RemoveField(
            model_name='addtrips',
            name='tripdate',
        ),
        migrations.RemoveField(
            model_name='addtrips',
            name='washing_charges_tank',
        ),
        migrations.AlterField(
            model_name='tripexpense',
            name='trip_general_expenses',
            field=models.IntegerField(null=True),
        ),
    ]
