# Generated by Django 5.2.1 on 2025-07-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_hwitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hwitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
