# Generated by Django 5.1.6 on 2025-03-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_remove_addtrips_bhatta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='End_Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_ends', models.CharField(max_length=200, null=True)),
                ('driver', models.CharField(max_length=200, null=True)),
                ('date', models.DateField()),
                ('end_Date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EndTrip',
        ),
        migrations.RemoveField(
            model_name='addtrips',
            name='percent',
        ),
    ]
