# Generated by Django 5.1.6 on 2025-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_end_trip_delete_endtrip_remove_addtrips_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=300, null=True)),
                ('gst', models.CharField(max_length=300, null=True)),
                ('pan', models.CharField(max_length=300, null=True)),
                ('tanker', models.CharField(max_length=200, null=True)),
                ('From_add', models.CharField(max_length=200, null=True)),
                ('To_add', models.CharField(max_length=200, null=True)),
                ('date_dis', models.DateField()),
                ('bill_no', models.IntegerField(null=True)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fo_date', models.DateField()),
                ('To_date', models.DateField()),
                ('d_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('par_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_d', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
