# Generated by Django 5.2.1 on 2025-07-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_de_invoice_de_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='MTInvoice',
        ),
        migrations.DeleteModel(
            name='MTItem',
        ),
    ]
