# Generated by Django 5.1.6 on 2025-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_gemini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemini',
            name='Fo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gemini',
            name='To_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gemini',
            name='d_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gemini',
            name='par_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gemini',
            name='total_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
