# Generated by Django 5.1.6 on 2025-03-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_gemini_fo_date_alter_gemini_to_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemini',
            name='amount_in',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
