# Generated by Django 5.1.6 on 2025-03-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_gemini_amount_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemini',
            name='d_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gemini',
            name='par_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gemini',
            name='total_d',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
