# Generated by Django 5.1.6 on 2025-03-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_alter_gemini_d_rate_alter_gemini_par_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemini',
            name='bill_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gemini',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gemini',
            name='date_dis',
            field=models.DateField(blank=True, null=True),
        ),
    ]
