# Generated by Django 5.2.1 on 2025-07-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_akinvioce_akitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='de_invoice',
            name='unloadcharge',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='de_invoice',
            name='unloadrate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
