# Generated by Django 5.1.6 on 2025-03-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_remove_gemini_amount_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_expense',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip_expense',
            name='subCategory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
