# Generated by Django 5.2.1 on 2025-07-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_de_invoice_unloadcharge_de_invoice_unloadrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='de_invoice',
            name='subtotal',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
