# Generated by Django 5.2.1 on 2025-07-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_de_invoice_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='de_invoice',
            name='subtotal',
        ),
    ]
