# Generated by Django 5.1.6 on 2025-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_alter_trip_expense_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_expense',
            name='part_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
