# Generated by Django 5.2.1 on 2025-07-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_remove_de_invoice_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='de_invoice',
            name='g_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
