# Generated by Django 5.1.6 on 2025-03-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_alter_gemini_company_alter_gemini_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemini',
            name='lr_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
