# Generated by Django 5.2.1 on 2025-07-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_de_invoice_g_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='de_invoice',
            name='g_amount',
        ),
    ]
