# Generated by Django 5.2.1 on 2025-07-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_remove_de_invoice_g_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='de_invoice',
            name='g_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
