# Generated by Django 5.1.6 on 2025-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_gemini_lr_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAkIndia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('gst', models.CharField(blank=True, max_length=300, null=True)),
                ('pan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanker', models.CharField(max_length=200, null=True)),
                ('tanker_cap', models.CharField(max_length=200, null=True)),
                ('From_add', models.CharField(max_length=200, null=True)),
                ('To_add', models.CharField(max_length=200, null=True)),
                ('date_dis', models.DateField(blank=True, null=True)),
                ('load', models.IntegerField(blank=True, null=True)),
                ('unload', models.IntegerField(blank=True, null=True)),
                ('short', models.IntegerField(blank=True, null=True)),
                ('retn', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lr_no', models.IntegerField(blank=True, null=True)),
                ('Fo_date', models.DateField(blank=True, null=True)),
                ('To_date', models.DateField(blank=True, null=True)),
                ('d_rate', models.IntegerField(blank=True, null=True)),
                ('par_day', models.IntegerField(blank=True, null=True)),
                ('total_d', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='gemini',
            old_name='Fo_date',
            new_name='union_charge',
        ),
        migrations.RemoveField(
            model_name='gemini',
            name='To_date',
        ),
        migrations.RemoveField(
            model_name='gemini',
            name='d_rate',
        ),
        migrations.RemoveField(
            model_name='gemini',
            name='par_day',
        ),
        migrations.RemoveField(
            model_name='gemini',
            name='total_d',
        ),
    ]
