# Generated by Django 5.1.6 on 2025-03-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_aakindia_rename_fo_date_gemini_union_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemini',
            name='union_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
