# Generated by Django 5.1.6 on 2025-03-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_alter_gemini_union_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aakindia',
            name='From_add',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aakindia',
            name='To_add',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aakindia',
            name='tanker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aakindia',
            name='tanker_cap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
