# Generated by Django 5.1.6 on 2025-03-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_trip_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
