# Generated by Django 5.1.6 on 2025-03-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_remove_expense_timestamp_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='To_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='from_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
