# Generated by Django 5.2.1 on 2025-07-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_asl_invoice_remove_aitem_invoice_asl_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asl_invoice',
            name='tmsid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
