# Generated by Django 5.1.6 on 2025-03-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_trip_to_id_trip_from_id_trip_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(max_length=50),
        ),
    ]
