# Generated by Django 5.2.1 on 2025-07-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_cd_invoice_cd_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd_invoice',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
