# Generated by Django 5.1.6 on 2025-03-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_trip_tanker_alter_trip_trip_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='Trips',
        ),
    ]
