# Generated by Django 5.1.6 on 2025-03-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_rename_trip_trips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trips',
            new_name='Trip',
        ),
    ]
