# Generated by Django 5.1.6 on 2025-03-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_rename_trips_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ashland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('gst', models.CharField(blank=True, max_length=300, null=True)),
                ('pan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanker', models.CharField(blank=True, max_length=200, null=True)),
                ('tanker_cap', models.CharField(blank=True, max_length=200, null=True)),
                ('From_add', models.CharField(blank=True, max_length=200, null=True)),
                ('To_add', models.CharField(blank=True, max_length=200, null=True)),
                ('date_dis', models.DateField(blank=True, null=True)),
                ('kg', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lr_no', models.IntegerField(blank=True, null=True)),
                ('Fo_date', models.DateField(blank=True, null=True)),
                ('To_date', models.DateField(blank=True, null=True)),
                ('d_rate', models.IntegerField(blank=True, null=True)),
                ('par_day', models.IntegerField(blank=True, null=True)),
                ('total_d', models.IntegerField(blank=True, null=True)),
                ('tank_c', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
