# Generated by Django 5.1.6 on 2025-03-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_ashland'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashland',
            name='total_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
