# Generated by Django 5.1.6 on 2025-03-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_alter_ashland_total_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aakindia',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
