# Generated by Django 5.1.6 on 2025-03-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_alter_aakindia_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashland',
            name='total_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
