# Generated by Django 5.2.1 on 2025-07-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_grninvoice_grnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hbitem',
            name='unit_price',
            field=models.IntegerField(default=1),
        ),
    ]
