# Generated by Django 5.2.1 on 2025-07-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_alter_hbitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hbitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
