# Generated by Django 5.1.6 on 2025-03-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_tripgemini'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripAdani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankerno', models.CharField(max_length=100)),
                ('From_address', models.CharField(max_length=200)),
                ('To_address', models.CharField(max_length=200)),
                ('drivername', models.CharField(max_length=100)),
                ('tank_capacity', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('dispatch_time', models.DateTimeField(blank=True, null=True)),
                ('reach_time', models.DateTimeField(blank=True, null=True)),
                ('unload_time', models.DateTimeField(blank=True, null=True)),
                ('lr_num', models.IntegerField(blank=True, null=True)),
                ('lr_date', models.DateField(blank=True, null=True)),
                ('freight_bill', models.IntegerField(blank=True, null=True)),
                ('freight_date', models.DateField(blank=True, null=True)),
                ('loaded_qty', models.IntegerField(blank=True, null=True)),
                ('unload_qty', models.IntegerField(blank=True, null=True)),
                ('short_qty', models.IntegerField(blank=True, null=True)),
                ('short_allow', models.IntegerField(blank=True, null=True)),
                ('return_qty', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
    ]
