# Generated by Django 5.2.1 on 2025-07-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_hinvoice_remove_hbwitem_invoice_hitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hinvoice',
            name='total_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
