# Generated by Django 5.1.6 on 2025-03-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_invoice_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
