# Generated by Django 5.2.1 on 2025-07-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_adminvioce_admitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminvioce',
            name='d_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
