# Generated by Django 5.1.6 on 2025-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0101_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_name',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
