# Generated by Django 5.2.1 on 2025-07-24 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_alter_adminvioce_d_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VVFMInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('gst', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VVFMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('tanker', models.CharField(max_length=100)),
                ('date_dis', models.DateField()),
                ('from_add', models.CharField(max_length=255)),
                ('to_add', models.CharField(max_length=255)),
                ('lr_no', models.CharField(max_length=100)),
                ('sac', models.CharField(max_length=20)),
                ('item_quantity', models.FloatField()),
                ('tanker_cap', models.FloatField()),
                ('unload', models.FloatField()),
                ('short', models.FloatField()),
                ('retn', models.FloatField()),
                ('item_unit_price', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.vvfminvoice')),
            ],
        ),
    ]
