# Generated by Django 5.1.6 on 2025-03-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_rename_customer_name_invoice_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='company_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
