# Generated by Django 5.2.1 on 2025-07-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_vvfminvoice_vvfmitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vvfmitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='VVFMInvoice',
        ),
        migrations.DeleteModel(
            name='VVFMItem',
        ),
    ]
