# Generated by Django 5.1.6 on 2025-03-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_rename_description_item_t_add_item_f_add_item_lr_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dispatch_d',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
