# Generated by Django 5.1.6 on 2025-03-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0105_item_dispatch_d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='t_add',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dispatch_d',
        ),
        migrations.RemoveField(
            model_name='item',
            name='f_add',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lr_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tanker_no',
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
