# Generated by Django 5.2.1 on 2025-07-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0105_verinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verinvoice',
            old_name='unit_price',
            new_name='price',
        ),
    ]
