# Generated by Django 5.1.6 on 2025-03-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_rename_t_add_item_description_remove_item_dispatch_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_in_words',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
