# Generated by Django 5.2.1 on 2025-07-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_rename_unit_price_verinvoice_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VERInvoice',
        ),
    ]
