# Generated by Django 5.2.1 on 2025-07-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_verinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verinvoice',
            name='total_price',
        ),
    ]
