# Generated by Django 5.1.6 on 2025-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_alter_harkaran_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harkaran',
            name='bill_no',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
