# Generated by Django 5.2.1 on 2025-07-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_remove_verinvoice_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='vertexInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='vertexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app.invoice')),
            ],
        ),
        migrations.DeleteModel(
            name='VERInvoice',
        ),
    ]
