# Generated by Django 5.2.1 on 2025-07-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_vertexinvoice_vertexitem_delete_verinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vertexinvoice',
            name='invoice_date',
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='From_add',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='To_add',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='date_dis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='fright_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='g_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='gst',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='lr_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='pan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='retn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='sac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='tanker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vertexinvoice',
            name='total_in_words',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vertexinvoice',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='vertexItem',
        ),
    ]
