# Generated by Django 5.1.6 on 2025-03-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_alter_harkaran_bill_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harkaran',
            old_name='bill_no',
            new_name='bill',
        ),
    ]
