# Generated by Django 5.1.6 on 2025-03-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_rename_bill_no_harkaran_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankerno', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('f_date', models.DateField(blank=True, null=True)),
                ('p_date', models.DateField(blank=True, null=True)),
                ('drivername', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
