# Generated by Django 5.2.1 on 2025-07-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_verinvoice_delete_vertexinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verinvoice',
            name='total_price',
        ),
    ]
