# Generated by Django 5.1.6 on 2025-03-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_driver_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_salary',
            name='t_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
