# Generated by Django 5.2.1 on 2025-07-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0113_remove_verinvoice_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verinvoice',
            name='description',
        ),
    ]
