# Generated by Django 5.1.6 on 2025-03-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0113_driver_salary_t_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver_salary',
            old_name='salary',
            new_name='salary_driver',
        ),
    ]
