# Generated by Django 5.1.6 on 2025-03-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_rename_salary_driver_salary_salary_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Harkaran',
        ),
    ]
