# Generated by Django 5.2.1 on 2025-07-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_remove_verinvoice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VertexBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VertexBillBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.vertexbill')),
            ],
        ),
    ]
