# Generated by Django 5.1.6 on 2025-03-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_delete_harkaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='harkaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('gst', models.CharField(blank=True, max_length=300, null=True)),
                ('pan', models.CharField(blank=True, max_length=300, null=True)),
                ('tanker', models.CharField(max_length=200, null=True)),
                ('From_add', models.CharField(max_length=200, null=True)),
                ('To_add', models.CharField(max_length=200, null=True)),
                ('date_dis', models.DateField(blank=True, null=True)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lr_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
