# Generated by Django 5.2.1 on 2025-07-25 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_vertexbill_vertexbillbillitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VertexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.vertexbill')),
            ],
        ),
        migrations.DeleteModel(
            name='VertexBillBillItem',
        ),
    ]
