# Generated by Django 5.2.1 on 2025-07-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_vertexitem_delete_vertexbillbillitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vertexitem',
            name='bill',
        ),
        migrations.DeleteModel(
            name='VertexBill',
        ),
        migrations.DeleteModel(
            name='VertexItem',
        ),
    ]
