# Generated by Django 5.1.6 on 2025-03-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_bill_cargill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargill',
            name='bill',
        ),
    ]
