# Generated by Django 5.1.6 on 2025-03-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_remove_cargill_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargill',
            name='company',
        ),
        migrations.RemoveField(
            model_name='cargill',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cargill',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='cargill',
            name='pan',
        ),
        migrations.AddField(
            model_name='bill',
            name='pan',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
