# Generated by Django 5.2.1 on 2025-07-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_vvfminvoice_vvfmitem_delete_verinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='Fo_date',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='To_date',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='c_gst',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='d_rate',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='hsac',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='i_gst',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='par_day',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='s_gst',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='total_d',
        ),
    ]
