# Generated by Django 5.1.6 on 2025-03-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_remove_cargill_company_remove_cargill_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargill',
        ),
    ]
