# Generated by Django 5.1.6 on 2025-03-19 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_delete_cargill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanker', models.CharField(max_length=200, null=True)),
                ('From_add', models.CharField(max_length=200, null=True)),
                ('To_add', models.CharField(max_length=200, null=True)),
                ('date_dis', models.DateField(blank=True, null=True)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lr_no', models.IntegerField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bill')),
            ],
        ),
    ]
