# Generated by Django 5.2.1 on 2025-07-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_remove_vvfmitem_from_add_remove_vvfmitem_to_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='From_add',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='To_add',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='date_dis',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='lr_no',
        ),
        migrations.RemoveField(
            model_name='vvfminvoice',
            name='tanker',
        ),
        migrations.AddField(
            model_name='vvfmitem',
            name='From_add',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vvfmitem',
            name='To_add',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vvfmitem',
            name='date_dis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vvfmitem',
            name='lr_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vvfmitem',
            name='tanker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
