# Generated by Django 5.1.6 on 2025-03-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_cargill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargill',
            new_name='Cargill_m',
        ),
    ]
