# Generated by Django 5.1.6 on 2025-03-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_rename_cargill_cargill_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargill_m',
            name='bill',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Cargill_m',
        ),
    ]
