# Generated by Django 5.2.1 on 2025-07-26 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0123_vertexinvoice_vertexitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALLANAInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('gst', models.CharField(blank=True, max_length=300, null=True)),
                ('pan', models.CharField(blank=True, max_length=300, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_in_words', models.CharField(blank=True, max_length=255)),
                ('sac', models.IntegerField(blank=True, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fright_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('g_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ALLANAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanker', models.CharField(blank=True, max_length=200, null=True)),
                ('load', models.IntegerField(blank=True, null=True)),
                ('unload', models.IntegerField(blank=True, null=True)),
                ('short', models.IntegerField(blank=True, null=True)),
                ('retn', models.IntegerField(blank=True, null=True)),
                ('From_add', models.CharField(blank=True, max_length=200, null=True)),
                ('To_add', models.CharField(blank=True, max_length=200, null=True)),
                ('date_dis', models.DateField(blank=True, null=True)),
                ('lr_no', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.allanainvoice')),
            ],
        ),
    ]
