# Generated by Django 5.1.6 on 2025-03-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0124_bill_tankerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
