# Generated by Django 5.1.6 on 2025-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0125_alter_trip_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripgemini',
            name='freight_bill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
