# Generated by Django 5.2.1 on 2025-07-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0125_aakdeinvoice_aakdeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aakdeitem',
            name='charges',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
