# Generated by Django 5.1.6 on 2025-03-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_alter_tripgemini_freight_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='aakindia',
            name='rate_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
