# Generated by Django 5.2.1 on 2025-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_aakdeitem_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aakdeitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
