# Generated by Django 5.1.6 on 2025-03-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_alter_addtrips_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrips',
            name='freight_bill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
