# Generated by Django 5.2.1 on 2025-07-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0128_mor_invoice_mor_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mor_item',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='MOR_Invoice',
        ),
        migrations.DeleteModel(
            name='MOR_Item',
        ),
    ]
