# Generated by Django 5.2.1 on 2025-07-30 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0130_mor_invoice_mor_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAKRMInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=300, null=True)),
                ('gst', models.CharField(blank=True, max_length=300, null=True)),
                ('pan', models.CharField(blank=True, max_length=300, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_in_words', models.CharField(blank=True, max_length=255)),
                ('tanker', models.CharField(blank=True, max_length=200, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('sac', models.IntegerField(blank=True, null=True)),
                ('Fo_date', models.DateField(blank=True, null=True)),
                ('To_date', models.DateField(blank=True, null=True)),
                ('d_rate', models.IntegerField(blank=True, null=True)),
                ('par_day', models.IntegerField(blank=True, null=True)),
                ('total_d', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fright_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('charges', models.CharField(blank=True, max_length=300, null=True)),
                ('g_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_mt', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AAKRMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanker_no', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('From_add', models.CharField(blank=True, max_length=200, null=True)),
                ('To_add', models.CharField(blank=True, max_length=200, null=True)),
                ('lrno', models.CharField(blank=True, max_length=200, null=True)),
                ('totalkm', models.IntegerField(blank=True, null=True)),
                ('diesel', models.IntegerField(blank=True, null=True)),
                ('dieselrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dieselamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urearate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ureaamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toll', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.aakrminvoice')),
            ],
        ),
    ]
