# Generated by Django 5.1.6 on 2025-03-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0131_remove_expense_description_alter_expense_toll_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
