# Generated by Django 5.2.1 on 2025-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0131_aakrminvoice_aakrmitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aakrminvoice',
            name='hsac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
