# Generated by Django 5.2.1 on 2025-07-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0132_aakrminvoice_hsac'),
    ]

    operations = [
        migrations.AddField(
            model_name='aakrminvoice',
            name='c_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='aakrminvoice',
            name='i_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='aakrminvoice',
            name='s_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
