# Generated by Django 5.2.1 on 2025-07-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0133_aakrminvoice_c_gst_aakrminvoice_i_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aakrminvoice',
            name='To_date',
        ),
        migrations.RemoveField(
            model_name='aakrminvoice',
            name='d_rate',
        ),
        migrations.RemoveField(
            model_name='aakrminvoice',
            name='par_day',
        ),
    ]
