# Generated by Django 5.2.1 on 2025-08-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0134_remove_aakrminvoice_to_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aakrminvoice',
            name='f_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
