# Generated by Django 5.2.1 on 2025-08-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0135_aakrminvoice_f_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='aakrminvoice',
            name='Scharges',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='aakrminvoice',
            name='Stotal_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
