# Generated by Django 5.1.6 on 2025-03-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0135_invoice_fo_date_invoice_from_add_invoice_to_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Fo_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='From_add',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='To_add',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='To_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='d_rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_dis',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lr_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='par_day',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='retn',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='short',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tanker',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tanker_cap',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_d',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='unload',
        ),
    ]
