# Generated by Django 5.2.1 on 2025-08-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0136_aakrminvoice_scharges_aakrminvoice_stotal_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='aakrminvoice',
            name='SFo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aakrminvoice',
            name='Shsac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
