# Generated by Django 5.1.6 on 2025-03-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0137_item_fo_date_item_from_add_item_to_add_item_to_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Fo_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='From_add',
        ),
        migrations.RemoveField(
            model_name='item',
            name='To_add',
        ),
        migrations.RemoveField(
            model_name='item',
            name='To_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='d_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_dis',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lr_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='par_day',
        ),
        migrations.RemoveField(
            model_name='item',
            name='retn',
        ),
        migrations.RemoveField(
            model_name='item',
            name='short',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tanker',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tanker_cap',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_d',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unload',
        ),
    ]
