# Generated by Django 5.2.1 on 2025-08-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0137_aakrminvoice_sfo_date_aakrminvoice_shsac'),
    ]

    operations = [
        migrations.AddField(
            model_name='aakrminvoice',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
