# Generated by Django 5.1.6 on 2025-03-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0139_invoice_fo_date_invoice_from_add_invoice_to_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
