# Generated by Django 5.2.1 on 2025-08-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0139_driver_locationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankerno', models.CharField(max_length=100)),
                ('From_address', models.CharField(max_length=200, null=True)),
                ('To_address', models.CharField(max_length=200, null=True)),
                ('drivername', models.CharField(max_length=100, null=True)),
                ('trip_date', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('load', models.IntegerField(blank=True, null=True)),
                ('unload', models.IntegerField(blank=True, null=True)),
                ('short_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allow_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_short', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('short_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('previous_loan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driverloan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DriverLoan',
        ),
    ]
