# Generated by Django 5.2.1 on 2025-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0140_driverl_delete_driverloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='aakrminvoice',
            name='all_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
