# Generated by Django 5.2.1 on 2025-08-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0141_aakrminvoice_all_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aakrminvoice',
            name='all_total',
        ),
    ]
