# Generated by Django 5.1.6 on 2025-03-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0141_driverloan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverloan',
            old_name='total',
            new_name='total_loan',
        ),
    ]
