# Generated by Django 5.1.6 on 2025-03-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0142_rename_total_driverloan_total_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverloan',
            old_name='total_loan',
            new_name='total',
        ),
    ]
