# Generated by Django 5.2.1 on 2025-08-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0145_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashname', models.CharField(max_length=150)),
                ('cashdate', models.DateField()),
                ('cashamount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
