# Generated by Django 5.2.1 on 2025-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0146_cashvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashvoucher',
            name='To',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cashvoucher',
            name='from_add',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cashvoucher',
            name='loadingdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashvoucher',
            name='tankerno',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cashvoucher',
            name='cashamount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cashvoucher',
            name='cashname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
