# Generated by Django 5.1.6 on 2025-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0146_alter_driverloan_actual_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='short_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
