# Generated by Django 5.2.1 on 2025-08-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0147_cashvoucher_to_cashvoucher_from_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashvoucher',
            name='remark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
