# Generated by Django 5.1.6 on 2025-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0147_alter_driverloan_short_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='driverloan',
            name='previous_loan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
