# Generated by Django 5.2.1 on 2025-08-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0148_cashvoucher_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtrips',
            name='dofreight_bill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addtrips',
            name='dofreight_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addtrips',
            name='dolr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addtrips',
            name='dolr_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
