# Generated by Django 5.1.6 on 2025-03-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0149_alter_driverloan_actual_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
