# Generated by Django 5.1.6 on 2025-03-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0150_alter_driverloan_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='actual_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
