# Generated by Django 5.2.1 on 2025-09-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0150_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverl',
            name='repayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driverl',
            name='short_allow_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
