# Generated by Django 5.2.1 on 2025-09-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0151_driverl_repayment_driverl_short_allow_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverl',
            name='remaining_amo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
