# Generated by Django 5.1.6 on 2025-03-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0151_alter_expense_actual_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='allow_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='driverloan',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
