# Generated by Django 5.2.1 on 2025-09-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0152_driverl_remaining_amo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='driverid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
