# Generated by Django 5.1.6 on 2025-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0153_alter_driverloan_short_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloan',
            name='actual_short',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
