# Generated by Django 5.2.1 on 2025-09-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0153_payment_driverid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tanker',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
