# Generated by Django 5.1.6 on 2025-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0154_alter_driverloan_actual_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='To_via',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='from_via',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tripadani',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
