# Generated by Django 5.2.1 on 2025-11-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0154_payment_tanker'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverl',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='driverl',
            name='driverid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='driverl',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='driverl',
            name='rdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverl',
            name='tanker',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='To_via',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='from_via',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='To_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='from_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
