# Generated by Django 5.2.1 on 2025-11-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0155_driverl_amount_driverl_driverid_driverl_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='drname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
