# Generated by Django 5.1.6 on 2025-03-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0155_trip_to_via_trip_from_via_alter_tripadani_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(max_length=50),
        ),
    ]
