# Generated by Django 5.2.1 on 2025-11-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0156_expense_drname'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetails',
            name='ddriver',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
