# Generated by Django 5.2.1 on 2025-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0157_plandetails_ddriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtrips',
            name='ddriver',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
