# Generated by Django 5.2.1 on 2025-12-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0158_addtrips_ddriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtrips',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
