# Generated by Django 5.1.6 on 2025-03-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0158_alter_trip_trip_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='To_via',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='from_via',
        ),
        migrations.AddField(
            model_name='expense',
            name='To_via',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='from_via',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
