# Generated by Django 5.2.1 on 2025-12-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0159_addtrips_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tanker_no', models.CharField(max_length=50)),
                ('driver', models.CharField(max_length=100)),
                ('load_mt', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm')], max_length=10)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='app.party')),
            ],
        ),
    ]
