# Generated by Django 5.1.6 on 2025-03-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0159_remove_trip_to_via_remove_trip_from_via_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
