# Generated by Django 5.1.6 on 2025-03-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0160_alter_expense_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='urea_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
