# Generated by Django 5.1.6 on 2025-03-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0161_alter_expense_urea_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
