# Generated by Django 5.1.6 on 2025-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0162_alter_trip_trip_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AakLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankerno', models.CharField(max_length=100)),
                ('From_address', models.CharField(max_length=200)),
                ('To_address', models.CharField(max_length=200)),
                ('drivername', models.CharField(max_length=100)),
                ('tank_capacity', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('dispatch_time', models.DateTimeField(blank=True, null=True)),
                ('reach_time', models.DateTimeField(blank=True, null=True)),
                ('unload_time', models.DateTimeField(blank=True, null=True)),
                ('lr_num', models.IntegerField(blank=True, null=True)),
                ('lr_date', models.DateField(blank=True, null=True)),
                ('freight_bill', models.IntegerField(blank=True, null=True)),
                ('freight_date', models.DateField(blank=True, null=True)),
                ('loaded_qty', models.IntegerField(blank=True, null=True)),
                ('unload_qty', models.IntegerField(blank=True, null=True)),
                ('short_qty', models.IntegerField(blank=True, null=True)),
                ('return_qty', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('time_Loading', models.IntegerField(blank=True, null=True)),
                ('time_Loading_mama', models.IntegerField(blank=True, null=True)),
                ('unloading_ganesh', models.IntegerField(blank=True, null=True)),
                ('unloading_mama', models.IntegerField(blank=True, null=True)),
                ('returned', models.DateTimeField(blank=True, null=True)),
                ('trip_ganesh', models.IntegerField(blank=True, null=True)),
                ('trip_mama', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
