# Generated by Django 5.1.6 on 2025-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0163_aaklocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='aaklocal',
            name='short_allow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
