# Generated by Django 5.1.6 on 2025-03-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0164_aaklocal_short_allow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaklocal',
            name='drivername',
        ),
        migrations.RemoveField(
            model_name='aaklocal',
            name='unload_time',
        ),
    ]
