# Generated by Django 5.1.6 on 2025-03-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0165_remove_aaklocal_drivername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaklocal',
            name='freight_bill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aaklocal',
            name='lr_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
