# Generated by Django 5.1.6 on 2025-03-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0166_alter_aaklocal_freight_bill_alter_aaklocal_lr_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
