# Generated by Django 5.1.6 on 2025-04-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0167_expense_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetails',
            name='tanker_capacity',
            field=models.CharField(max_length=200),
        ),
    ]
