# Generated by Django 5.1.6 on 2025-04-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0168_alter_plandetails_tanker_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdriver_details',
            name='adharnumber',
            field=models.BigIntegerField(),
        ),
    ]
