# Generated by Django 5.1.6 on 2025-04-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0169_alter_newdriver_details_adharnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='gst',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='pan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
