# Generated by Django 5.1.6 on 2025-04-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0170_companydetails_gst_companydetails_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanker_no', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField(max_length=15)),
                ('tdate', models.DateField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
            ],
        ),
    ]
