# Generated by Django 5.1.6 on 2025-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0171_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='vehicle_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
