# Generated by Django 5.1.6 on 2025-04-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0172_tracking_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='tanker_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
