# Generated by Django 5.1.6 on 2025-04-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0173_alter_tracking_tanker_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='tanker_no',
            field=models.CharField(max_length=100),
        ),
    ]
