# Generated by Django 5.1.6 on 2025-04-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0174_alter_tracking_tanker_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtrips',
            old_name='tank_capacity',
            new_name='tanker_capacity',
        ),
    ]
