# Generated by Django 5.1.6 on 2025-04-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0175_rename_tank_capacity_addtrips_tanker_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtrips',
            old_name='tanker_capacity',
            new_name='tank_capacity',
        ),
    ]
