# Generated by Django 5.1.6 on 2025-04-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0176_rename_tanker_capacity_addtrips_tank_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='tankercap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
