# Generated by Django 5.1.6 on 2025-04-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0177_add_vehicle_tankercap'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
