# Generated by Django 5.1.6 on 2025-04-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0178_add_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrips',
            name='tankerno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='app.plandetails'),
        ),
    ]
