# Generated by Django 5.1.6 on 2025-04-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0182_alter_addtrips_tankerno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.AlterField(
            model_name='addbank_loan',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
