# Generated by Django 5.1.6 on 2025-04-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0183_delete_loan_alter_addbank_loan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanker', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_contract', models.CharField(blank=True, max_length=255, null=True)),
                ('finance_by', models.CharField(blank=True, max_length=255, null=True)),
                ('pamount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('famount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ddate', models.DateField(blank=True, null=True)),
                ('pdate', models.DateField(blank=True, null=True)),
                ('days', models.CharField(blank=True, max_length=150, null=True)),
                ('bank', models.CharField(blank=True, max_length=150, null=True)),
                ('ramount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
