# Generated by Django 5.1.6 on 2025-04-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0184_addloan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TankerCapacity',
        ),
        migrations.AlterField(
            model_name='driverloan',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
