# Generated by Django 5.1.6 on 2025-04-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0185_delete_tankercapacity_alter_driverloan_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addloan',
            old_name='tanker',
            new_name='tankerno',
        ),
    ]
