# Generated by Django 5.1.6 on 2025-04-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0186_rename_tanker_addloan_tankerno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_tenure_months', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TankerCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Addloan',
        ),
        migrations.AlterField(
            model_name='driverloan',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
