# Generated by Django 5.1.6 on 2025-04-14 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0187_loan_tankercapacity_delete_addloan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrips',
            name='tankerno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plandetails'),
        ),
    ]
