# Generated by Django 5.1.6 on 2025-04-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0188_alter_addtrips_tankerno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrips',
            name='tankerno',
            field=models.CharField(max_length=100),
        ),
    ]
