# Generated by Django 5.1.6 on 2025-04-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0190_addloan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newdriver_details',
            old_name='name',
            new_name='drivername',
        ),
    ]
