# Generated by Django 5.1.6 on 2025-04-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0191_rename_name_newdriver_details_drivername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandetails',
            name='drivername',
        ),
        migrations.AddField(
            model_name='plandetails',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.newdriver_details'),
        ),
    ]
