# Generated by Django 5.1.6 on 2025-04-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0192_remove_plandetails_drivername_plandetails_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdriver_details',
            name='drivername',
        ),
        migrations.RemoveField(
            model_name='plandetails',
            name='driver',
        ),
        migrations.AddField(
            model_name='newdriver_details',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plandetails',
            name='drivername',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
