# Generated by Django 5.1.6 on 2025-04-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0193_remove_newdriver_details_drivername_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=200, null=True)),
                ('cityname', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
