# Generated by Django 5.1.6 on 2025-04-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0195_city_state_delete_statecity_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrips',
            name='short_allow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
