# Generated by Django 5.1.6 on 2025-04-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0196_alter_addtrips_short_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdriver_details',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
