# Generated by Django 5.1.6 on 2025-04-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0197_newdriver_details_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandetails',
            name='drivername',
        ),
        migrations.AddField(
            model_name='plandetails',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newdriver_details'),
        ),
    ]
