# Generated by Django 5.1.6 on 2025-04-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0199_newdriver_details_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandetails',
            name='driver',
        ),
        migrations.AddField(
            model_name='plandetails',
            name='drivername',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
