# Generated by Django 5.1.6 on 2025-04-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0202_alter_plandetails_drivername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetails',
            name='drivername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.newdriver_details'),
        ),
    ]
