# Generated by Django 5.1.6 on 2025-04-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0203_alter_plandetails_drivername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetails',
            name='drivername',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
