# Generated by Django 5.1.6 on 2025-04-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0204_alter_plandetails_drivername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdriver_details',
            name='phone',
        ),
        migrations.AddField(
            model_name='newdriver_details',
            name='fname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
