# Generated by Django 5.1.6 on 2025-04-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0205_remove_newdriver_details_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtrips',
            name='tankerno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
