# Generated by Django 5.1.6 on 2025-04-17 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0207_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
