# Generated by Django 5.1.6 on 2025-04-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0208_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='total_expense',
            new_name='f_trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_time',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='drivername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='chassise_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='engine_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
