# Generated by Django 5.1.6 on 2025-04-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0209_rename_total_expense_trip_f_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
