# Generated by Django 5.1.6 on 2025-05-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0211_rename_toll_name_toll_details_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
