# Generated by Django 5.1.6 on 2025-05-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0212_remove_order_company_delete_company_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Clientgemini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('tanker_type', models.CharField(blank=True, max_length=200, null=True)),
                ('tanker_cpa', models.CharField(blank=True, max_length=200, null=True)),
                ('fadd', models.CharField(blank=True, max_length=200, null=True)),
                ('tadd', models.CharField(blank=True, max_length=200, null=True)),
                ('ddate', models.DateField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
