# Generated by Django 5.1.6 on 2025-05-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0213_bills_clientgemini'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bills',
        ),
    ]
