# Generated by Django 5.1.6 on 2025-05-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0215_billing_itemsss'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='gst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='pan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
