# Generated by Django 5.1.6 on 2025-05-13 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0219_bills_remove_itemsss_bill_billitem_delete_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.bills'),
        ),
    ]
