# Generated by Django 5.1.6 on 2025-05-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0220_alter_billitem_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
