# Generated by Django 5.1.6 on 2025-05-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0221_invoice_cgst_invoice_grand_total_invoice_sgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
