# Generated by Django 5.1.6 on 2025-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0222_invoice_sac'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='charges',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hsac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
