# Generated by Django 5.1.6 on 2025-05-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0223_invoice_charges_invoice_hsac'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
