# Generated by Django 5.1.6 on 2025-05-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0225_alter_item_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
