# Generated by Django 5.1.6 on 2025-05-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0226_alter_item_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='c_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='i_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='s_gst',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
