# Generated by Django 5.1.6 on 2025-05-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0227_invoice_c_gst_invoice_i_gst_invoice_s_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tanker_cap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
