# Generated by Django 5.1.6 on 2025-05-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0228_alter_invoice_tanker_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='g_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
