# Generated by Django 5.1.6 on 2025-05-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0229_invoice_g_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fright_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
