# Generated by Django 5.1.6 on 2025-05-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0231_cargillinvoice_cargillitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargillitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='CargillInvoice',
        ),
        migrations.DeleteModel(
            name='CargillItem',
        ),
    ]
