# Generated by Django 5.1.6 on 2025-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0233_ginvoice_gitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ginvoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
