# Generated by Django 5.1.6 on 2025-05-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0235_alter_ginvoice_cgst_alter_ginvoice_igst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ginvoice',
            name='total_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
