# Generated by Django 5.1.6 on 2025-05-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0237_ainvoice_aitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='fitness_img',
            field=models.FileField(null=True, upload_to='fitness/'),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='insurance_img',
            field=models.FileField(null=True, upload_to='insurance/'),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='national_img',
            field=models.FileField(null=True, upload_to='national/'),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='puc_img',
            field=models.FileField(null=True, upload_to='puc/'),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='state_img',
            field=models.FileField(null=True, upload_to='state/'),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='tax_img',
            field=models.FileField(null=True, upload_to='tax/'),
        ),
    ]
