# Generated by Django 5.1.6 on 2025-05-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0238_add_vehicle_fitness_img_add_vehicle_insurance_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_vehicle',
            name='vehicle_img',
        ),
    ]
