# Generated by Django 5.1.6 on 2025-05-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0243_cinvoice_citem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinvoice',
            name='token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
