# Generated by Django 5.1.6 on 2025-05-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0246_cinvoice_citem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='CInvoice',
        ),
        migrations.DeleteModel(
            name='CItem',
        ),
    ]
