# Generated by Django 5.1.6 on 2025-05-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0249_alter_cainvoice_c_gst_alter_cainvoice_cgst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caitem',
            name='invoice',
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='aTo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='ad_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='ahsac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='apar_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='atotal_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='CaInvoice',
        ),
        migrations.DeleteModel(
            name='CaItem',
        ),
    ]
