# Generated by Django 5.1.6 on 2025-05-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0250_remove_caitem_invoice_ainvoice_ato_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainvoice',
            name='acharges',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
