# Generated by Django 5.1.6 on 2025-05-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0251_ainvoice_acharges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ainvoice',
            name='aTo_date',
        ),
        migrations.RemoveField(
            model_name='ainvoice',
            name='acharges',
        ),
        migrations.RemoveField(
            model_name='ainvoice',
            name='ad_rate',
        ),
        migrations.RemoveField(
            model_name='ainvoice',
            name='ahsac',
        ),
        migrations.RemoveField(
            model_name='ainvoice',
            name='apar_day',
        ),
        migrations.RemoveField(
            model_name='ainvoice',
            name='atotal_d',
        ),
    ]
