# Generated by Django 5.1.6 on 2025-05-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0252_remove_ainvoice_ato_date_remove_ainvoice_acharges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainvoice',
            name='t_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='total_t',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='tpar_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
