# Generated by Django 5.1.6 on 2025-05-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0253_ainvoice_t_rate_ainvoice_total_t_ainvoice_tpar_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainvoice',
            name='tcharges',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ainvoice',
            name='thsac',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
