# Generated by Django 5.1.6 on 2025-05-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0254_ainvoice_tcharges_ainvoice_thsac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ainvoice',
            name='lr_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ginvoice',
            name='lr_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lr_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
