# Generated by Django 5.1.6 on 2025-05-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0256_aak_out_invoice_aak_out_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aak_out_Invoice',
            new_name='Aak_in_Invoice',
        ),
        migrations.RenameModel(
            old_name='Aak_out_Item',
            new_name='Aak_in_Item',
        ),
    ]
