# Generated by Django 5.1.6 on 2025-05-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0257_rename_aak_out_invoice_aak_in_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aak_in_invoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aak_in_item',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
