# Generated by Django 5.1.6 on 2025-05-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0258_alter_aak_in_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aak_in_item',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
